version: '3'

services:
  nuxt-app:
    image: 'nuxt-app:1.0'
    container_name: 'test1'
    restart: 'always'
    ports:
      - '8002:3000'
    env_file:
      - .env.production
    # environment:
    #   - BASE_URL=http://192.168.112.129:3000
